[2025-04-04 07:27:44] Unexpected response from app.py: 404
